### ISSUE TITLE
Insert a database record alongisde file upload to disk?

### ISSUE THREAD

**Issue by incorpusyehtee** [olaferlandsen/FileUpload-for-PHP#4]
I was trying to have this script handle the files uploading to disk because it seems very good at what it was built for. Unfortunately (due to lack of experience with PHP probably) I cannot figure out how to also insert an SQL record in the same form submission.

So for instance I tried doing something like

```
<form method="post" action="" enctype="multipart/form-data" accept-charset="utf-8">
	<p>Name</p>
		<input type="text" name="new_name" />
	<p>File</p>
		<input type="file" name="new_file" />
	<input type="submit" value="Upload now!" />
</form>
```

with all of the same statements as the example upload document you have in this repository. In my PHP I put a record insert statement from the form submission:

```
if (isset($_POST['submit'])) {

echo 'test';

$link = mysqli_connect("host", "user", "password", "database");	
$insert_name = mysqli_real_escape_string($link, $_REQUEST['new_name']);

$sql = "INSERT INTO table (id, name, file) VALUES (NULL, '$insert_name', '$filename')";	

if(mysqli_query($link, $sql)){
		echo "Records added successfully.";
	} else{
		echo "ERROR: Could not able to execute $sql. " . mysqli_error($link);
	}
	mysqli_close($link);
	
}
```

I did try to  simplify things for debugging and found that any statement (including `echo` statements) would not render on a page where your script was used for uploading files if they were inside the `if (isset($_POST['submit'])) {` block.

The files upload to disk and are named/located properly, but the database insert does not happen. Any ideas would be much appreciated! Thanks for the great script!

**Comment by olaferlandsen** [comment]
Hi @incorpusyehtee thanks for writing!
To store the filename on you database, try with: 
```php
<?php
        $file = new FileUpload\FileUpload();
        $file->setInput( "new_file" ); // you input file name
        $file->save();
        if ($file->getStatus()) {
              $getInfo = $file->getInfo(); // get information about file

              $link = mysqli_connect("host", "user", "password", "database");
              $insert_name = mysqli_real_escape_string($link, $getInfo->filename); // get filename
              $filename = mysqli_real_escape_string($link, $getInfo->destination); // get full path
              $sql = "INSERT INTO table (id, name, file) VALUES (NULL, '$insert_name', '$filename')";
              if(mysqli_query($link, $sql)){
                  echo "Records added successfully.";
              } else{
		  echo "ERROR: Could not able to execute $sql. " . mysqli_error($link);
	      }
        }
?>
```

Please see [FileUpload::getInfo()](https://github.com/olaferlandsen/FileUpload-for-PHP#fileuploadgetinfo-)

Bye!

**Comment by segunmicheal27** [comment]
how can we print file error with this class

**Comment by olaferlandsen** [comment]
@segunmicheal27 you can use: 
https://github.com/olaferlandsen/FileUpload-for-PHP#fileuploadgetinfo-

And, if you want get status:
https://github.com/olaferlandsen/FileUpload-for-PHP#fileuploadgetstatus-

please, tell me if it help you.
