### ISSUE TITLE
Multiple files

### ISSUE THREAD

**Issue by josvenes** [olaferlandsen/FileUpload-for-PHP#5]
Is it possible to (by changing the code) to upload multiplefiles??

**Comment by olaferlandsen** [comment]
Well, for now no... Can you help me with this feature? :D 
Thanks!!

**Comment by josvenes** [comment]
i will look into it [😊]

//Jos


Verzonden vanuit Outlook<http://aka.ms/weboutlook>


________________________________
Van: Olaf Erlandsen <notifications@github.com>
Verzonden: maandag 24 april 2017 20:26
Aan: olaferlandsen/FileUpload-for-PHP
CC: josvenes; Author
Onderwerp: Re: [olaferlandsen/FileUpload-for-PHP] Multiple files (#5)


Well, for now no... Can you help me with this feature? :D
Thanks!!
